import React from 'react';
import { DeveloperProfileData } from '../../data/galaxyData';
import { X, Award, GraduationCap, Mail, Phone, Sparkles, ArrowUpRight } from 'lucide-react';

interface ResumeModalProps { onClose: () => void; }

export const ResumeModal: React.FC<ResumeModalProps> = ({ onClose }) => (
  <div className="fixed inset-0 z-50 flex items-center justify-center bg-[#030610]/82 p-4 backdrop-blur-xl" role="dialog" aria-modal="true" aria-label="Developer dossier" onMouseDown={(e) => { if (e.target === e.currentTarget) onClose(); }}>
    <div className="relative max-h-[90vh] w-full max-w-4xl overflow-y-auto rounded-[1.75rem] border border-cyan-200/25 bg-[#080d18]/96 p-5 text-slate-100 shadow-[0_30px_120px_rgba(0,0,0,0.55)] backdrop-blur-2xl sm:p-8">

      <div className="pointer-events-none absolute right-0 top-0 h-72 w-72 rounded-full bg-cyan-400/10 blur-3xl" />
      <button type="button" onClick={(e) => { e.preventDefault(); e.stopPropagation(); onClose(); }} className="absolute right-5 top-5 z-50 rounded-xl border border-white/10 bg-white/10 p-2.5 text-slate-300 cursor-pointer transition hover:bg-white/20 hover:text-white" aria-label="Close developer dossier"><X className="h-5 w-5" /></button>

      <div className="relative mb-7 flex flex-col gap-5 border-b border-white/10 pb-7 sm:flex-row sm:items-center"><div className="flex h-20 w-20 shrink-0 items-center justify-center rounded-[1.5rem] bg-gradient-to-br from-cyan-200 to-violet-300 font-heading text-3xl font-black text-slate-950 shadow-xl shadow-cyan-400/15">PB</div><div><div className="mb-2 flex items-center gap-2 font-mono text-[10px] font-bold uppercase tracking-[0.16em] text-cyan-200"><Sparkles className="h-3.5 w-3.5" /> Developer dossier / profile signal</div><h2 className="text-3xl font-black leading-tight text-white sm:text-4xl">{DeveloperProfileData.name}</h2><p className="mt-1 max-w-2xl text-sm font-semibold leading-5 text-cyan-100">{DeveloperProfileData.title}</p><p className="mt-2 max-w-2xl text-xs leading-5 text-slate-400">{DeveloperProfileData.tagline}</p></div></div>

      <div className="relative grid gap-5 lg:grid-cols-[1.15fr_0.85fr]"><div className="space-y-6"><section><p className="mb-3 font-mono text-[10px] font-bold uppercase tracking-[0.16em] text-slate-400">The short version</p><p className="rounded-2xl border border-cyan-200/15 bg-cyan-200/[0.05] p-4 text-sm leading-6 text-slate-300">{DeveloperProfileData.summary}</p></section><section><h3 className="mb-3 flex items-center gap-2 font-mono text-[10px] font-bold uppercase tracking-[0.16em] text-cyan-200"><GraduationCap className="h-4 w-4" /> Academic foundation</h3><div className="space-y-2">{DeveloperProfileData.education.map((education) => <div key={education.degree} className="rounded-2xl border border-white/8 bg-white/[0.025] p-4"><p className="text-sm font-bold leading-5 text-white">{education.degree}</p><p className="mt-1 font-mono text-[10px] text-slate-500">{education.institution} <span className="text-cyan-200">· {education.period}</span></p></div>)}</div></section></div><div className="space-y-6"><section><h3 className="mb-3 flex items-center gap-2 font-mono text-[10px] font-bold uppercase tracking-[0.16em] text-violet-200"><Award className="h-4 w-4" /> Verified credentials</h3><div className="space-y-2">{DeveloperProfileData.certifications.map((certification) => <div key={certification} className="flex items-start gap-2.5 rounded-xl border border-white/8 bg-white/[0.025] p-3 text-xs leading-5 text-slate-300"><span className="mt-0.5 text-emerald-200">✓</span>{certification}</div>)}</div></section><section className="grid grid-cols-2 gap-2">{[['7.5k', 'students mentored'], ['90%', 'placement outcome'], ['25', 'trainers led'], ['08', 'flagship projects']].map(([value, label]) => <div key={label} className="rounded-2xl border border-white/8 bg-white/[0.025] p-3"><strong className="block text-xl font-black text-white">{value}</strong><span className="font-mono text-[9px] uppercase tracking-wide text-slate-500">{label}</span></div>)}</section></div></div>

      <div className="relative mt-7 flex flex-wrap gap-2 border-t border-white/10 pt-6 font-mono text-xs"><a href={DeveloperProfileData.linkedin} target="_blank" rel="noopener noreferrer" className="signal-button flex items-center gap-2 rounded-xl border border-cyan-200/25 bg-cyan-200/10 px-4 py-3 font-bold text-cyan-100">LinkedIn <ArrowUpRight className="h-3.5 w-3.5" /></a><a href={DeveloperProfileData.github} target="_blank" rel="noopener noreferrer" className="signal-button flex items-center gap-2 rounded-xl border border-violet-200/25 bg-violet-200/10 px-4 py-3 font-bold text-violet-100">GitHub <ArrowUpRight className="h-3.5 w-3.5" /></a><a href={`mailto:${DeveloperProfileData.email}`} className="flex items-center gap-2 rounded-xl border border-white/10 bg-white/5 px-4 py-3 text-slate-300 transition hover:bg-white/10"><Mail className="h-4 w-4 text-rose-200" /> Email</a><a href={`tel:${DeveloperProfileData.phone}`} className="flex items-center gap-2 rounded-xl border border-white/10 bg-white/5 px-4 py-3 text-slate-300 transition hover:bg-white/10"><Phone className="h-4 w-4 text-emerald-200" /> Call</a></div>
    </div>
  </div>
);
